# This is a basic workflow to help you get started with Actions

name: Run Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  - push
  - pull_request

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test: ['yarn test', 'yarn test:forking']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup environment
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup repository
        run: |
          cp ci.env .env
          echo "PROVIDER_FORKING=${{ secrets.PROVIDER_FORKING_MAINNET }}" >> .env
          yarn install --update-checksums
          yarn compile
      - name: Run tests
        run: ${{ matrix.test }}
